# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160722_0429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='truncated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='entities',
        ),
    ]
