# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160722_0442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='tweet',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Confirmation / Verification'), (1, 'Tracking'), (2, 'Refund'), (3, 'Status Order'), (4, 'OTP')], null=True),
        ),
    ]
